import Vue from 'vue'
import { Button, Card, Cell, CellGroup, Image, Row, Col, List, PullRefresh, Grid,NavBar,Swipe,SwipeItem,Stepper,Lazyload,Toast,Field } from 'vant'

Vue.use(Button)
Vue.use(Card)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Image)
Vue.use(Row)
Vue.use(Col)
Vue.use(List)
Vue.use(PullRefresh)
Vue.use(Grid)
Vue.use(NavBar)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Stepper)
Vue.use(Lazyload)
Vue.use(Toast)
Vue.use(Field)
